namespace: ns-n-tier-app
image:
  pullPolicy: IfNotPresent
  repository: gcr.io/google-samples/hello-frontend
  tag: 1.0
container:
  name: frontend
ingress:
  host: my-n-tier-app.io
  path: /
  pathType: prefix
  port: http
service:
  name: frontend-service
  port: 80
  protocol: TCP
  targetPort: 80
  type: ClusterIP
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
