apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Chart.name }}
  labels:
    {{- include "application.selectorLabels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  name: {{ .Values.ingress.port }}
